### DevolucionesApp — ciclo de vida de solicitudes
### Auth: JWT Bearer (Parte 4)

@baseUrl = http://localhost:8080

### 0) Login analista
# @name loginAnalista
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "analista1",
  "password": "Password123!"
}

###
@tokenAnalista = {{loginAnalista.response.body.access_token}}

### 0b) Login supervisor
# @name loginSupervisor
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "supervisor1",
  "password": "Password123!"
}

###
@tokenSupervisor = {{loginSupervisor.response.body.access_token}}

### Health
GET {{baseUrl}}/actuator/health

### 1) Crear solicitud (BORRADOR)
# @name crear
POST {{baseUrl}}/api/v1/solicitudes
Authorization: Bearer {{tokenAnalista}}
Content-Type: application/json

{
  "rutCliente": "6876966-3",
  "nombreCliente": "FELIPE SOTO MORALES",
  "monto": 150000.00,
  "bancoDestino": "BANCO ESTADO",
  "cuentaDestino": "627820024292"
}

###
@id = {{crear.response.body.id}}

### 2) Enviar a revisión
POST {{baseUrl}}/api/v1/solicitudes/{{id}}/enviar
Authorization: Bearer {{tokenAnalista}}

### 3) Aprobar (supervisor distinto al creador)
POST {{baseUrl}}/api/v1/solicitudes/{{id}}/aprobar
Authorization: Bearer {{tokenSupervisor}}

### 4) Pagar
POST {{baseUrl}}/api/v1/solicitudes/{{id}}/pagar
Authorization: Bearer {{tokenSupervisor}}

### 5) Historial
GET {{baseUrl}}/api/v1/solicitudes/{{id}}/historial
Authorization: Bearer {{tokenAnalista}}

### 6) Transición inválida (409) — pagar de nuevo
POST {{baseUrl}}/api/v1/solicitudes/{{id}}/pagar
Authorization: Bearer {{tokenSupervisor}}

### 7) Analista intenta aprobar (403)
# @name crear2
POST {{baseUrl}}/api/v1/solicitudes
Authorization: Bearer {{tokenAnalista}}
Content-Type: application/json

{
  "rutCliente": "15558837-3",
  "nombreCliente": "VALENTINA TORRES",
  "monto": 20000.00,
  "bancoDestino": "ITAU",
  "cuentaDestino": "111"
}

###
@id2 = {{crear2.response.body.id}}

POST {{baseUrl}}/api/v1/solicitudes/{{id2}}/enviar
Authorization: Bearer {{tokenAnalista}}

###
POST {{baseUrl}}/api/v1/solicitudes/{{id2}}/aprobar
Authorization: Bearer {{tokenAnalista}}

### 8) Listado con filtros
GET {{baseUrl}}/api/v1/solicitudes?estado=PAGADA&page=0&size=10
Authorization: Bearer {{tokenAnalista}}
